name: Database Test CI/CD

on:
  push:
    branches: ["test"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --junitxml=path/to/test-results/results.xml

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-test-results
          path: path/to/test-results/

      - name: Deploy to S3 Test Bucket
        run: |
          aws s3 cp path/to/db-build/ s3://saayam-virginia-qa-private/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
