name: k6 Benchmarking

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: ./.github/actions/checkout

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 Benchmark
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          k6 run tests/k6/benchmarking.js
