name: DAST Scan

on:
  push:
    branches: [ qa ]
  pull_request:
    branches: [ qa ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://your-qa-url.example.com'
          cmd_options: '-a'
          fail_action: true