name: DAST Scan

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run OWASP ZAP Scan
        run: |
          chmod +x scripts/run-zap.sh
          ./scripts/run-zap.sh

      - name: Upload reports to S3
        run: |
          chmod +x scripts/upload-to-s3.sh
          ./scripts/upload-to-s3.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}